// Generated by CoffeeScript 1.6.3
(function() {
  var fontello, fs, needle, path, print, unzip;

  fs = require('fs');

  needle = require('needle');

  print = require('util').print;

  path = require('path');

  unzip = require('unzip');

  fontello = {
    install: function(options) {
      var data, host;
      host = 'http://fontello.com';
      data = {
        config: {
          file: options.config,
          content_type: 'application/json'
        }
      };
      return needle.post(host, data, {
        multipart: true
      }, function(error, response, body) {
        var sessionId, zipFile;
        if (error) {
          throw error;
        }
        sessionId = body;
        if (response.statusCode === 200) {
          zipFile = needle.get("" + host + "/" + sessionId + "/get", function(error, response, body) {
            if (error) {
              throw error;
            }
          });
          if (options.css && options.font) {
            return zipFile.pipe(unzip.Parse()).on('entry', (function(entry) {
              var cssPath, dirName, fileName, fontPath, pathName, type, _ref;
              pathName = entry.path, type = entry.type;
              if (type === 'File') {
                dirName = (_ref = path.dirname(pathName).match(/\/([^\/]*)$/)) != null ? _ref[1] : void 0;
                fileName = path.basename(pathName);
                switch (dirName) {
                  case 'css':
                    cssPath = path.join(options.css, fileName);
                    return entry.pipe(fs.createWriteStream(cssPath));
                  case 'font':
                    fontPath = path.join(options.font, fileName);
                    return entry.pipe(fs.createWriteStream(fontPath));
                  default:
                    return entry.autodrain();
                }
              }
            })).on('finish', (function() {
              return print('Install complete.\n'.green);
            }));
          } else {
            return zipFile.pipe(unzip.Extract({
              path: '.'
            })).on('finish', (function() {
              return print('Install complete.\n'.green);
            }));
          }
        }
      });
    }
  };

  module.exports = fontello;

}).call(this);
