// Generated by CoffeeScript 1.6.3
(function() {
  var colors, fontello, fs, needle, pjson, print, program, unzip;

  colors = require('colors');

  fs = require('fs');

  needle = require('needle');

  print = require('util').print;

  program = require('commander');

  pjson = require("" + __dirname + "/../package.json");

  unzip = require('unzip');

  fontello = function() {
    program.version(pjson.version).usage('install').option('-c, --config [path]', 'path to fontello config');
    program.command('install').description('download fontello').action(function(env, options) {
      var data, host;
      host = 'http://fontello.com';
      data = {
        config: {
          file: program.config || 'config.json',
          content_type: 'application/json'
        }
      };
      return needle.post(host, data, {
        multipart: true
      }, function(error, response, body) {
        var sessionId;
        if (error) {
          throw error;
        }
        sessionId = body;
        if (response.statusCode === 200) {
          return needle.get("" + host + "/" + sessionId + "/get", function(error, response, body) {
            if (error) {
              throw error;
            }
          }).pipe(unzip.Extract({
            path: '.'
          })).on('finish', (function() {
            return print("Download complete.\n".green);
          }));
        }
      });
    });
    return program.parse(process.argv);
  };

  module.exports = fontello;

}).call(this);
